version: '3'
services:
  react-webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #not map use the folder in the container already
      - .:/app
  react-webapp-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules #not map use the folder in the container already
      - .:/app
    command: ["npm", "run", "test"]